description: Generates a summary of the workbook, including key insights and relevant
  visual aids, using natural language processing or machine learning techniques, such
  as BERT or GPT-3.
name: SummaryGenerator
parameters:
  model_type: gpt3
  summary_length: 150
